[package]
name = "prime_web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.13.0"
askama = "0.15.5"
clap = { version = "4.6.0", features = ["derive"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.33.0"
rusqlite = { version = "0.39.0", features = ["bundled", "chrono"] }
serde = { version = "1.0.228", features = ["derive"] }
