[package]
name = "my-grep"
version = "0.1.0"
edition = "2024"

[package.metadata.component]
package = "component:my-grep"

[package.metadata.component.dependencies]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }
